### ISSUE TITLE
Recommended Changes + Some information about some bugs.

### ISSUE THREAD

**Issue by jdev082** [Darth-Ness/Ink#18]
As for the bug, line numbers don't necessarily break entirely when switching tabs. When text is entered after switching tabs the line numbers come back.

Also, some fancy vertical tabs on the side instead of the top would look cool!

**Comment by Darth-Ness** [comment]
Thanks for the info about the bug. I think I can fix it now. My sidebar component isn't very good, so until I can make a better one; I will leave the tabs at the top. Plus, I'm not sure how a three paned workspace would work.

**Comment by Darth-Ness** [comment]
As of version 4 vertical tabs are included.
