### ISSUE TITLE
Some recommendations for the design...

### ISSUE THREAD

**Issue by jdev082** [Darth-Ness/Ink#3]
First off, the rounded corner border around the selected side of the page doesn't look all that great. I think just a single line between the two to separate them would look nicer.

Having some space between the border and the HTML/Text on the right side would improve the looks as well.

Other than that it's good... enough.

**Comment by jdev082** [comment]
Also, I don't think the glow around the buttons is very good looking. But I'm pretty sure that's the framework. I'd recommend removing it but you don't have to. Also the shading/shadow under the buttons adding depth, not modern under my standards but also optional.

**Comment by Darth-Ness** [comment]
> Also, I don't think the glow around the buttons is very good looking. But I'm pretty sure that's the framework. I'd recommend removing it but you don't have to. Also the shading/shadow under the buttons adding depth, not modern under my standards but also optional.

Like that?
