### ISSUE TITLE
"Natural" in Theme Selector Mispelled

### ISSUE THREAD

**Issue by jdev082** [Darth-Ness/Ink#4]
![image](https://user-images.githubusercontent.com/92550746/151449461-591b3c72-337b-429e-b952-e2a5b2e1888b.png)
The new UI is amazing btw!!!

"Natural" is mispelled.

**Comment by Darth-Ness** [comment]
> ![image](https://user-images.githubusercontent.com/92550746/151449461-591b3c72-337b-429e-b952-e2a5b2e1888b.png) The new UI is amazing btw!!!
> 
> "Natural" is mispelled.

Thanks! I fix in a second.
