### ISSUE TITLE
Switching themes breaks Comet theme

### ISSUE THREAD

**Issue by jdev082** [Darth-Ness/Ink#5]
To reproduce the bug

1. Click theme selector
![image](https://user-images.githubusercontent.com/92550746/151472860-e428bf40-5351-4ce8-8e8b-e28ac3a43e8b.png)
2. Click any theme other than comet
3. Change the theme back to comment
# Comet working properly
![image](https://user-images.githubusercontent.com/92550746/151472930-80990361-00bb-4db5-9e92-639f267df35c.png)
# Comet when reproducing the bug
![image](https://user-images.githubusercontent.com/92550746/151472982-263a5b2f-f7bd-4189-8c6f-14312ba3e4ac.png)

**Comment by jdev082** [comment]
Components Affected:
Theme Switcher
Version:
N/A, Release Unidentified
Bugged File:
main.js

Browser bug was found on: Firefox 95.0
OS: Linux 64

**Comment by imdevarsh** [comment]
You should make the title shorter: `Switching themes breaks Comet theme`

It looks similar to the Space theme but not exactly.

**Comment by imdevarsh** [comment]
The theme is actually Nord by default.

**Comment by jdev082** [comment]
I'd also recommend a separate CSS file instead of styled div's and style tags.

**Comment by imdevarsh** [comment]
@JaydenDev The theme isn't called Comet, it's called Nord. Comet is the purple one. Nord is the default one. I rearranged it in #6

**Comment by Darth-Ness** [comment]
Let me explain this bug. Basically it happens when you select a theme other than Nord. On refresh, the theme is reset, but the drop down box is not.

**Comment by Darth-Ness** [comment]
I requested changes to be made on the PR.
